#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""


"""
    This script runs a series of integration tests for the voice_interaction node. 
    It can be launched with the integration_test launch file and it will output
    how many tests are to be run and the results for each test. 
"""

import rospy
import rospkg
import rosnode
import rostopic
import rosservice
import time
import os
import numpy as np
from std_msgs.msg import String
from geometry_msgs.msg import Twist, Vector3
from audio_common_msgs.msg import AudioData

WAV_HEADER_LENGTH = 24
AUDIO_ASSETS_DIR = rospkg.RosPack().get_path('voice_interaction_robot') + "/assets"
AUDIO_EXTENSION = ".wav"

class IntegrationTest:
    wait_between_audio_commands = 1
    
    def __init__(self, text_input_publisher, audio_input_publisher, test_type, commands, expected_result):
        self.text_input_publisher = text_input_publisher
        self.audio_input_publisher = audio_input_publisher
        self.test_type = test_type
        self.commands = commands
        self.expected_result = expected_result

    def __str__(self):
        return "IntegrationTest(test_type=%s, commands=%s)" % (self.test_type, self.commands, )

    def run_test(self):
        test_runners = {
            'text': self.run_text_input_test,
            'audio': self.run_audio_input_test
        }
        test_runners[self.test_type]()
        
    def run_text_input_test(self):
        for command in self.commands:
            self.send_text(command)
            
    def send_text(self, text):
        self.text_input_publisher.publish(text)
        
    def run_audio_input_test(self):
        for filename in self.commands:
            self.send_audio(filename)
            time.sleep(self.wait_between_audio_commands)
        
    def send_audio(self, filename):
        full_path = AUDIO_ASSETS_DIR + "/" + filename + AUDIO_EXTENSION
        raw_data = self.load_wav_file(full_path)
        if raw_data is not None:
            audio_data = raw_data.tolist() 
            self.audio_input_publisher.publish(audio_data)

    def load_wav_file(self, filepath):
        if not os.path.exists(filepath):
            print("Could not find file " + filepath)
            return None
        data = np.fromfile(open(filepath), np.uint8)[WAV_HEADER_LENGTH:]
        return data

    def check_result(self, result):
        if result == self.expected_result:
            return True
        else:
            rospy.loginfo("{}, result:\n{}".format(self, result))
            rospy.loginfo("expected result:\n{}".format(self.expected_result))
            return False
        
class VoiceInteractionIntegrationTest:
    wake_words = ("jarvis", "turtlebot")
    last_cmd_vel = None
    vinode_start_timeout = 10
    test_sleep_time = 2
    tests = []
    max_retries_per_test = 1
    
    def __init__(self):
        rospy.init_node("integration_test", disable_signals=True)
        self.text_input_publisher = rospy.Publisher("/text_input", String, queue_size=5)
        self.audio_input_publisher = rospy.Publisher("/audio_input", AudioData, queue_size=5)
        self.wake_publisher = rospy.Publisher("/wake_word", String, queue_size=5)
        rospy.Subscriber("/cmd_vel", Twist, self.save_cmd_vel)
        
    def run_tests(self):
        self.wait_for_voice_interaction_nodes()
        self.wait_for_voice_interaction_services()
        self.wait_for_voice_interaction_node_to_subscribe_to_topic()
        self.load_text_input_tests()
        self.load_audio_input_tests()
        rospy.loginfo("Total tests: {}".format(len(self.tests)))
        # Before running any tests, wake the robot and wait for a slightly longer period of time.
        self.wake_robot(2.0)
        for test in self.tests:
            self.run_test(test)
        
    def run_test(self, test):
        self.wake_robot()
        retry_count = 0
        while retry_count <= self.max_retries_per_test:
            if retry_count > 0:
                rospy.loginfo("Retrying failed test {}".format(test))
                time.sleep(self.test_sleep_time)
            test.run_test()
            time.sleep(self.test_sleep_time)
            if test.check_result(self.last_cmd_vel):
                rospy.loginfo("test passed")
                return
            else:
                retry_count += 1

        rospy.loginfo("test failed")
        
    def wait_for_voice_interaction_nodes(self):
        required_nodes = set([
            '/lex_node', 
            '/voice_interaction', 
            '/voice_command_translator'
        ])
        while not required_nodes.issubset(rosnode.get_node_names()):
            time.sleep(0.1)
            
    def wait_for_voice_interaction_services(self):
        required_services = set([
            '/lex_node/lex_conversation'
        ])
        while not required_services.issubset(rosservice.get_service_list()):
            time.sleep(0.1)
            
    def wait_for_voice_interaction_node_to_subscribe_to_topic(self):
        rostopic.wait_for_subscriber(self.text_input_publisher, self.vinode_start_timeout)
        rostopic.wait_for_subscriber(self.wake_publisher, self.vinode_start_timeout)
            
    def load_text_input_tests(self):
        text_input_tests = [
            (["move", "forward", "5"], Twist(Vector3(5,0,0), Vector3(0,0,0))),
            (["move", "backwards", "0.2"], Twist(Vector3(-0.2,0,0), Vector3(0,0,0))),
            (["move forward 2"], Twist(Vector3(2,0,0), Vector3(0,0,0))),
            (["rotate left 10"], Twist(Vector3(0,0,0), Vector3(0,0,10))),
            (["rotate", "clockwise",  "5"], Twist(Vector3(0,0,0), Vector3(0,0,-5))),
            (["stop"], Twist(Vector3(0,0,0), Vector3(0,0,0))),
            (["halt"], Twist(Vector3(0,0,0), Vector3(0,0,0)))
        ]
        for test in text_input_tests:
            (command, expected_result) = test
            integration_test = IntegrationTest(self.text_input_publisher, self.audio_input_publisher, 
                "text", command, expected_result)
            self.tests.append(integration_test)
        
    def load_audio_input_tests(self):
        audio_input_tests = [
            (["move-forward-5"], Twist(Vector3(5,0,0), Vector3(0,0,0))),
            (["turn-clockwise-3"], Twist(Vector3(0,0,0), Vector3(0,0,-3))),
            (["stop"], Twist(Vector3(0,0,0), Vector3(0,0,0))),
            (["turn", "counterclockwise", "10"], Twist(Vector3(0,0,0), Vector3(0,0,10))),
            (["rotate", "clockwise", "5"], Twist(Vector3(0,0,0), Vector3(0,0,-5))),
        ]
        for test in audio_input_tests:
            (command, expected_result) = test
            integration_test = IntegrationTest(self.text_input_publisher, self.audio_input_publisher,
                "audio", command, expected_result)
            self.tests.append(integration_test)
            
    def wake_robot(self, post_wake_sleep=0.1):
        self.wake_publisher.publish(self.wake_words[0])
        time.sleep(post_wake_sleep)
        
    def save_cmd_vel(self, data):
        rospy.logdebug("Received new cmd_vel: {}".format(data))
        self.last_cmd_vel = data

def main():
    vi_integration_test = VoiceInteractionIntegrationTest()
    rospy.loginfo("Starting integration tests")
    vi_integration_test.run_tests()
    rospy.loginfo("Integration tests complete")


if __name__ == "__main__":
    main()
