sudo: required
language: generic
compiler:
- gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
env:
  matrix:
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  - ROS_DISTRO=melodic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
  - secure: Le73NtmI8FCnfqPVj8pxdcK+jMNZsDNk8oIn6/AqOcjS7kRmkMlQ2vkSLgVtt8Pgbj4AJ9bfSeQwP4/By6XGizAKNaG8tGMhXSjQVx5BdznBEhXU1+CDzAgT3FDcxNvgKGBCpiC/44CyTi3CDhbn7RkyalLFVGviLPr/niYSsNJtD+d1x7/xV1YdVPvQhyMvCFDEZ2QCF/SWzDClblqk6CI1f93JL1AFwLl91SdGoK8FHm2aIn7VaRWOW7ULzU1OZPHW89Xy0fYqn9/2CjqSoS4TJUR5tJP38AigeegFFq9UzA6lOgEamj0eS87exeLpwDY1KbB9/FMztAKDQWJuDL/cnMpXVlehEgsTBg5PRSAK3U7MSbckFRNbfd0XBpFKB60YPVj2BMux9lRY09bRSs2kjPl1APVmb6GyEEZsWuFhjD1QzepLitfyWjVnJ7iLeKeaKZLEXgELW3JBKImWnUNE0qQl7XPmxG8jWnnTez7KX2ncYfcSn+D4kn5VnarwDdRqJy+ZXBNPEAdehXaZABLCfZWwTMsNL00JKZEqw4OlZJLlSpVzQiMN33fpK5/u6n22Zys/12EcRlTiXGqxv7GOTj+klb3oUhI4yWtXccAGPkJRM55z7WI0N20dZwDEzRKQ00ncg+E8NsRH1E1oQTp4+Lq0otPutsiGXl/7drE=
  - secure: wwDWmSpQLL21F5QhZkiMkjMbMaaz5gFGYfHbVRmSQwMoKmitwMZ5xrr7ClwV5UPch/6uMo3f2mQR4UgcmSpwcJsUsRu7Vu/cp0C47UxER6wMz6rdvgTG0AtaS+eBKdZTh7z3ShlP6z2CkyAhvXCe6ZOrsBBOSAgwuPNixrSFlQ/Rob5j2tNRpfcMj4lK11aX446Vv05DewogSWz2gixBJb/eROXNolkuZmRWOKdJv1zxXe7luV/8TmXpdW6bNddmNntzHgOGNWCts4ZTi6pWtu15kqPPoRLbZRgbPehFzhuuNgMTLe2NQKIFVtZyBZrgNusWmXoXufDzoTAsdatRW6+zQ8S1cX/QEwscuvnURBQlkRgGnd/U7aFh6GcHlJ0v3Ez2C6LsuiwpQE/qe7odNg8ajnizH1/3ki8AiiuOoGTjtOcMPwqto9hVBmR6o8B4UEE17+Pmt9dUTY9smXO0AcRL5dFRPfAYjU+9fwbTwvtDuKeAxzvhwJltZP86C8kQ3utCZLnbyvo5tto+AJdzz7h/yeEB+vR893UP5bOhlyYLJut/5hAH3eSfTnNv72r5uuGRKc+/SsLh5IDSA1ypCQxaXNswGeM5ymuqIXie5TfiBQbzCUNxqciKJ2bT1EclMRuxOD7m/E9IAiVLmLKfOdhkaFGEBtra0dIPYFiF6DA=
  - SA_NAME=voice-interaction
  - SA_PACKAGE_NAME=voice_interaction_robot
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
before_install:
- pip install --user awscli
- openssl aes-256-cbc -K $encrypted_7930ef72e947_key -iv $encrypted_7930ef72e947_iv
  -in github_deploy.pem.enc -out github_deploy.pem -d
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- . .ros_ci/add_tag.sh
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- .ros_ci/ce_build.sh
- kill %1
before_deploy:
- . .ros_ci/before_deploy.sh
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$S3_BUCKET_NAME"
    region: "us-west-2"
    local_dir: shared
    skip_cleanup: true
    wait-until-deployed: true
    on:
      branch: master
    upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
  - provider: script
    script: bash .ros_ci/codepipeline_deploy.sh
    on:
      branch: master
after_deploy:
- .ros_ci/post_deploy.sh
