sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
    #- travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  global:
  - SA_NAME=voice-interaction
  - SA_PACKAGE_NAME=voice_interaction_robot
  - ROS_DISTRO=dashing
  - ROS_VERSION=2
  - GAZEBO_VERSION=9
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - secure: NvVI+SvtSArAJ10RzMQUztjMg8oUzXUMhilE5uO5CXTekf034ccH1dWCkex5cW9AOqQShRa3gErOdibOQIHN+jhCbGNfLCplcHImhJsE6PtUN0M5yO9R1onzIE9/G6p5/MRUYB0EnwvFoqL8tGNRP0IYf9xbUAA8ZirnU70d4j8GYNpIg/hMRqSKs7IdeGQn2XTRG3dUKDDCtGnf+KkcZArPmUXDj8ejs7mD6crq8w7zMtI6K7RKFSU8xST9JH2fyM2cl+tRYJcdsZWTvvJIBZP0IWxIE15R7G/AIRhPNK3ScN8VVQuebwg/Y+Jbu4YAM7PY34/4l/3+W1u2GcbmX7sZQC5V7SfwnLhk3kJJy75VPh9R7y1OxZFKhoP0wRAJe/7CS9lVL1iJP6h/9Nrrgdjy4mTUo1HNLk5kLJBUxo6YQ0U9ZdKjFV0salwT2BzUuner7dwbhxuzBx2OlVBGui+/upZH7aXc1o67fvCkUI499bFI8yNXG2adrUVX5ltKSAdSSeQAPhyweb9RzwQvYJbwlB5ZT+056rRe2jd60rMCutU80Zpow2W9B3QnYJbahshQSWDEGlmS7Y3dMh0jwTxO8zd/2e7KLn+VF5hAmzmPC9GLJZWHuPc2B7xffxSwGHuP6WVhzVVCFhCTwRp/Gak2Bt2o3/h1WzevqlXt56U=
  - secure: fOHPgDKA0atQSMquccxXitvGOU+YsowapMploddmgG/jF+uSeeFbBo6Q0mu1IdMkuzXr0w08dpsU6QFylvt/EGINNMSZSLhc072gLHsWpLbKIPJSY9Jm1lpqRUmxti9n7RYmt7Z2AUH/dG/nDJYlWO6ajDY30TOS8wo9ZG34CRN6tuHL9kXbey35qoZDc35iECuN0Ury0HTaAyL9ymivev/mpLGALe4zrsUk0in+pyAMabQCoBwp+qHerNqXeUrjkdfR7+WYql8yHs7tCyDlJmnqTigMuu1HzOAFH1pZ95EQrwseZF6bnVMtWCgrxxFKlXF371+tyf9U/zkkOFtCg7DcUQbMruJK8hJv5v0v7/dnX4aSE8Fw4/Io0ZbmnrRLW80tOLAginbEb/nlBOzzprA2QdeYQ4nY8fhALj8r/JHk5a0i3qVTZ0OC1avXyqSs4TnDyBKQZ6eYATdmvsdOXqwIkS3ELOiLDfbCfpv5OdrF29WqvNL9oT6hXzPWfwMzhd6AqvwaUJNqZjUiM9jJ2qt2+mj79o474lcAfOExiAmojTnSOu2ui+Rp8AC8c0cARpVrz+8jbYkZFzL9En/E7j0I/pKookzHJMH/tgnEkXP4fuJ8S88ICE1xClOnMpVbgBeQs5yiaE/Sfua/fu3pCY6pUXwop96KBleSCNu2Sxc=
before_install:
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- . .ros_ci/add_tag.sh && set +e
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- ".ros_ci/ce_build.sh"
- kill %1
before_deploy:
- . .ros_ci/before_deploy.sh && set +e
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  region: us-west-2
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  on:
    branch: ros2
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
jobs:
  include:
  - stage: Build & Bundle
    env: WORKSPACES="robot_ws" UPLOAD_SOURCES="false"
  - stage: Build & Bundle
    env: WORKSPACES="simulation_ws" UPLOAD_SOURCES="false"
  - stage: Upload sources
    script: . .ros_ci/add_tag.sh && .ros_ci/prepare_sources_to_upload.sh && set +e
    env: WORKSPACES="robot_ws simulation_ws"
  - stage: Deploy
    script: . .ros_ci/add_tag.sh && set +e
    before_deploy: export APP_MANIFEST_REPO=AppManifest-${SA_NAME}-${ROS_DISTRO}-gazebo${GAZEBO_VERSION}
    deploy:
    - provider: script
      script: bash .ros_ci/codepipeline_deploy.sh
      on:
        branch: ros2
after_deploy:
- ".ros_ci/post_deploy.sh"
