sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
    #- travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  global:
  - SA_NAME=voice-interaction
  - SA_PACKAGE_NAME=voice_interaction_robot
  - ROS_DISTRO=dashing
  - ROS_VERSION=2
  - GAZEBO_VERSION=9
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - secure: Nv2U7OwkwP5BaR6VB6QzFRZGkakz3UKfE8GsjOpWJZF7YRBBWo/1r4yWwLBYaJf8fhfSBpOcZ9nhHGj3YSjcEtqkcf5t4t3OorjmOMu375dvJgtUTKJaiO6gALBqFwpXhaNuQl3jALQdV/GxFEitxTto0r+WkAsPXA35W5ZisNBwjSkLitr/tE72OW6Daf+eKQpsIMmQVzAK8kmFL2NdO8KkCuYfDkR5Omw8sTHwpuMyeGSpES3d1NW3lR5U9Xq55PWUEPCSXQopTZgMWWb1S61bcjWjlj0Z7Ybf27jB8bG+MtI3BEzAiE5FsaKFwbj8vqaprK+mXZMqYobOnWAHNhbyVSsKYv+vyByKvvxWIQW0JTYRLGvKArvscaf/yqVqZqQvH72Kxe1kFLp2Ym2I/y7IzM42wgJG3CovRYe2PTvIZCSvQTKTARr8CJmM6u8GIAxVsGShVq6xqHi/cuPMN1xynkVo1gGMkD9u/bEiV1geXZb7vMtuiYDYMA52vkfa4ygxiuoR6Np5Ne+96F78vA2KuvdDK1f/seBDb2Lhu29YIDOH+1rdRUhH0wWkgi1GJUrsVivu+Bn4XC5zyNcbvvlLBvItwm6t81kwJ7vBWKZOJ7ebzFlW/m2fjDAzx9zzTMnW5+1mzIoDYWnBR22UT+Mu6ZiX+Da2i5NV1IAfxmc=
  - secure: aZiT84lLiSa4LHuVemJhBhYJb5DrQLAeO9gw4yp8ZqfHcMkjPiYJdedXqvLyux/lE/sMGsGbN+xU2D2jidbWjWBBusey/HomNdN/cNS2Mk0rBydnIjlusKjB3kTLLsjToUpIjXQnXYFxY+rf2Zi8Nr382Qv+a4HALkOjGjph+cYCGaHi4WE7S7Qi7Vs/ANOMtoGHdpuYOLO2gd7tjHt+Z6MyUCMWp3MIba0PTp635Ot0XiWuPZG7wwiTN4377tTKea94ETWGY8kAOV5H6xRcNgz2qziSOkkXQSU0UlOBhQRHY8dCvFh0hzh1WbRSS3Z0hl2aWtljai5WCO/xyLXcWpHX1WYpF6Ke6H5zvyPzAOejP8kTT/+xdqKfSMOv8C3LIBWpTNMdVatLxy74W7lzjnkQzhrnCU16ZaR0Zu7BLm8HWROb+zXnAkr2XRec0tvG722pFuKa1TTBykvnzVr+kAuFK9OO1ZcQ2t1nvhLC9J6d21C9j9i2PmlWmhtF1UKpgMfkcnib2e/LCVo0y483k7w764w+riMXJCJdHxSzL6zeq1pJM0SySFxGRkFDHFJAE6gfmSMcO0TZkJiDN4xYPTNztNPC8VpBi2O0tsaUx89YPskWfXGOUsjJd0dpX6c0iZxWbkPQhfXpMsOo2oUH5mD65+rMoZnW5BhVcvTvqcQ=
before_install:
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/add_tag.sh && set +e"
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- ".ros_ci/ce_build.sh"
- kill %1
before_deploy:
- ". .ros_ci/before_deploy.sh && set +e"
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  region: us-west-2
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  on:
    branch: ros2
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
jobs:
  include:
  - stage: Build & Bundle
    env: WORKSPACES="robot_ws" UPLOAD_SOURCES="false"
  - stage: Build & Bundle
    env: WORKSPACES="simulation_ws" UPLOAD_SOURCES="false"
  - stage: Upload sources
    script: ". .ros_ci/add_tag.sh && .ros_ci/prepare_sources_to_upload.sh && set +e"
    env: WORKSPACES="robot_ws simulation_ws"
  - stage: Deploy
    script: ". .ros_ci/add_tag.sh && set +e"
    before_deploy: export APP_MANIFEST_REPO=AppManifest-${SA_NAME}-${ROS_DISTRO}-gazebo${GAZEBO_VERSION}
    deploy:
    - provider: script
      script: bash .ros_ci/codepipeline_deploy.sh
      on:
        branch: ros2
after_deploy:
- ".ros_ci/post_deploy.sh"
