sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
env:
  global:
  - SA_NAME=voice-interaction
  - SA_PACKAGE_NAME=voice_interaction_robot
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - secure: GLHaDi+4OXmsEXP8UKwPFwa5vSUYclbAKH8SKr+hsGrDeuDqeHraByJMBI4bA2SPA3HHuVcB48P/Bya0Kfg+twD062DhkROmjt0OESBp0ksqbQy75xKvTlf4L3pnkmkKbhgIInLAY/e/fhGYNomqbb4B33SENQY2FqPz2t0nmjs4RyfF6EZpNyVLMXacdQEvi9TudJVYR+leclSfOr9qo3sx03WlJ3pc7g1K2p2xIvDX5GDKO/rWvuicekJAAsORjxM/cxAY5fyAlMVQ9BHtody8u/1wVM9m/e/FqkcdHHlpGNFi4ioHgcvQCSqMmSqfogOZnHsZatVD1T6/W0b5OWs5uvfEq5y5mH8rS6KtZIpe/V9mb3AAonxiDkPW1qas9bGs8eHnNtz3d+sf/AJ7WQNcAX2IZDwWRDrh0y/eiaqaOK0vLTOIUVuVQFEfFtUzN8DWGfPe2IZilxbl7XLzkZEVgVBJ+eEdDM07DU3MhDvuek2XYq9S6f4DWyNSWcls7/j7JZaSlOlAIA6omFOlbf7UpbTEMPDY/cIRParcO/aQLwsWx16wQqI9VLYrg76DJ8rEOE4shOZANZv2/Ai1KhwKLfggHl2iMGquOKdKn3gMrKaCkJU/z7VSGXRDoWa9yW0htjUrSoTNDwku5pR5DzOl3yEcnEaw7mgb1lrlJ5Q=
  - secure: UsSXAWcy+TrevV50dYVgrYOjKunhA9kn1Y85TlBezDjlbdZC/5S0M2863m8fI7Te9tTce7AhDPD7o/B1guz2JzhYk3dLoWlpy2/4mTRYHHK62snXe2RQmmmgNeWNX1HAjQLLHtwvnj7Ry7Tcc4jj5x2dh/M5ot8BsJlxqZt7gRaXWWaNnMZFbNz8ABphvFaTfH6ywOJDVUYm5idKj4XTcO9q6jAVHyOwcJ04hkBHyTdSi9nHl/Jq5zYwWXiN6uQXifa7Sv727ODVzD52lTqqD1dTDmbecTlg1z/yuKgZrBxAN1gFvAZ14DgByVWcAgp/QZ5sEP4sNYP6aMbZA/kawFWx7pjLvrsQG14TUKKZ4cNfxEJRa6e8DTiIijlyhpCrNZ1zb0P8zGEYR3ZvX8VuhnWIljzusFSZoDd19lc0yu40DK6wG4ewcCosDpgLH/Wp2IeBo52elAClTMMkAwiuwD8atK0HHycG0Q3GlR3Kb8gftpJFsj3hfIcWqIep79MgHf9Fu33OC5owN14XPHNCzr5OqTbmvnhP2MrKQE4Ifng9JbHYTUDzbCeiybelRnO5axrYPKlx8bAT+hu/I4ojbyYyEDbqujcTNx6Nepg8+ioucMwwnniY8CkpTYj//uIL/GcplMHe/Dq3tjf+Q5UclqlxFzg5R6bEy3IE1KgTAaU=
before_install:
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/add_tag.sh"
- set +e; while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- ".ros_ci/ce_build.sh"
- kill %1
before_deploy:
- ". .ros_ci/before_deploy.sh"
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  region: us-west-2
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  on:
    branch: ros2
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
jobs:
  include:
  - stage: Build & Bundle
    env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="robot_ws"
  - stage: Build & Bundle
    env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="simulation_ws"
  - stage: Deploy
    script: ". .ros_ci/add_tag.sh"
    env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9
    before_deploy: export APP_MANIFEST_REPO=AppManifest-${SA_NAME}-${ROS_DISTRO}-gazebo${GAZEBO_VERSION}
    deploy:
    - provider: script
      script: bash .ros_ci/codepipeline_deploy.sh
      on:
        branch: ros2
after_deploy:
- ".ros_ci/post_deploy.sh"
