#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import actionlib
import rospy
from std_msgs.msg import String
from tts.msg import SpeechAction, SpeechGoal
polly_client = actionlib.SimpleActionClient('tts', SpeechAction)


class VoiceOutput:
    def __init__(self, node_name):
        rospy.init_node(node_name)
        rospy.Subscriber("/" + node_name + "/speak", String, self.speak_text)

    def run(self):
        rospy.spin()

    def speak_text(self, data):
        text = data.data
        timeout = rospy.Duration(2)
        polly_client.wait_for_server(timeout=timeout)
        goal = SpeechGoal()
        goal.text = text
        goal.metadata = '{"voice_id": "Joey"}'
        rospy.loginfo("Polly Speaking Text: %s" % text)
        polly_client.send_goal(goal)


def main():
    try:
        voice_output = VoiceOutput(node_name="voice_output_node")
        voice_output.run()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
