#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

"""
This node processes fulfilled commands from lex and turns them into robot commands
"""

import rospy
from voice_interaction_robot_msgs.msg import FulfilledVoiceCommand
from geometry_msgs.msg import Twist

cmd_vel_publisher = rospy.Publisher('/cmd_vel', Twist, queue_size=10)


class VoiceCommandTranslator:
    slots = []

    def __init__(self):
        rospy.init_node("voice_command_translator")
        rospy.Subscriber('/voice_interaction_node/fulfilled_command', FulfilledVoiceCommand, self.handle_voice_command)

    def run(self):
        rospy.spin()

    def handle_voice_command(self, command):
        rospy.loginfo("Fulfilled lex command:")
        rospy.loginfo(command)
        response_handlers = {
            'hello': self.ignore,
            'move': self.move_handler,
            'turn': self.turn_handler,
            'stop': self.stop_handler,
        }
        self.slots = self.convert_slot_array_to_map(command.slots)
        if command.intent_name not in response_handlers:
            rospy.logwarn("Could not find handler for lex intent " + command.intent_name)
            return
        response_handlers[command.intent_name]()
    
    def convert_slot_array_to_map(self, slot_array):
        return {slot.key: slot.value for slot in slot_array}

    def ignore(self):
        pass

    def stop_handler(self):
        stop_command = Twist()
        cmd_vel_publisher.publish(stop_command)
        
    def move_handler(self):
        move_command = self.convert_response_to_move_command()
        rospy.loginfo("move command:")
        rospy.loginfo(move_command)
        cmd_vel_publisher.publish(move_command)
        
    def convert_response_to_move_command(self):
        twist = Twist()
        twist.linear.x = float(self.slots['move_rate'])
        if self.slots['move_direction'].startswith("back"):
            twist.linear.x *= -1
        return twist
        
    def turn_handler(self):
        turn_command = self.convert_response_to_turn_command()
        rospy.loginfo("turn command:")
        rospy.loginfo(turn_command)
        cmd_vel_publisher.publish(turn_command)
        
    def convert_response_to_turn_command(self):
        twist = Twist()
        twist.angular.z = float(self.slots['turn_rate'])
        if self.slots['turn_direction'].startswith("clock"):
            twist.angular.z *= -1
        return twist


def main():
    try:
        voice_command_translator = VoiceCommandTranslator()
        voice_command_translator.run()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
